/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen
* Do not edit the class manually.
*/

import Foundation
import CoreData

extension AdditionalPropertiesClass {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<AdditionalPropertiesClass> {
        return NSFetchRequest<AdditionalPropertiesClass>(entityName: "AdditionalPropertiesClass")
    }

    var mapProperty: ? {
        get { return getManagedValue(key: "mapProperty") as?  }
        set { setManagedValue(newValue, key: "mapProperty") }
    }
var mapOfMapProperty: Dictionary? {
        get { return getManagedValue(key: "mapOfMapProperty") as? Dictionary }
        set { setManagedValue(newValue, key: "mapOfMapProperty") }
    }

}
