/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen
* Do not edit the class manually.
*/

import Foundation
import CoreData

extension Animal {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<Animal> {
        return NSFetchRequest<Animal>(entityName: "Animal")
    }

    @NSManaged public var className: String {
        get { return getManagedValue(key: "className") as? String }
        set { setManagedValue(newValue, key: "className") }
    }
var color: String? {
        get { return getManagedValue(key: "color") as? String }
        set { setManagedValue(newValue, key: "color") }
    }

}
