/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen
* Do not edit the class manually.
*/

import Foundation
import CoreData

extension ApiResponse {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<ApiResponse> {
        return NSFetchRequest<ApiResponse>(entityName: "ApiResponse")
    }

    var code: Int32? {
        get { return getManagedValue(key: "code") as? Int32 }
        set { setManagedValue(newValue, key: "code") }
    }
var type: String? {
        get { return getManagedValue(key: "type") as? String }
        set { setManagedValue(newValue, key: "type") }
    }
var message: String? {
        get { return getManagedValue(key: "message") as? String }
        set { setManagedValue(newValue, key: "message") }
    }

}
