/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen
* Do not edit the class manually.
*/

import Foundation
import CoreData

extension ArrayTest {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<ArrayTest> {
        return NSFetchRequest<ArrayTest>(entityName: "ArrayTest")
    }

    @NSManaged public var arrayOfString: Set<>?
@NSManaged public var arrayArrayOfInteger: Set<Array>?
@NSManaged public var arrayArrayOfModel: Set<Array>?

}

// MARK: Generated accessors for arrayArrayOfInteger
extension ArrayTest {

    @objc(addArrayObject:)
    @NSManaged public func addArray(_ value: Array)

    @objc(removeArrayObject:)
    @NSManaged public func removeFromArray(_ value: Array)

    @objc(addArray:)
    @NSManaged public func addToArray(_ values: Set<Array>)

    @objc(removeArray:)
    @NSManaged public func removeFromArray(_ values: Set<Array>)
}

// MARK: Generated accessors for arrayArrayOfModel
extension ArrayTest {

    @objc(addArrayObject:)
    @NSManaged public func addArray(_ value: Array)

    @objc(removeArrayObject:)
    @NSManaged public func removeFromArray(_ value: Array)

    @objc(addArray:)
    @NSManaged public func addToArray(_ values: Set<Array>)

    @objc(removeArray:)
    @NSManaged public func removeFromArray(_ values: Set<Array>)
}
