/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen
* Do not edit the class manually.
*/

import Foundation
import CoreData

extension ArrayOfArrayOfNumberOnly {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<ArrayOfArrayOfNumberOnly> {
        return NSFetchRequest<ArrayOfArrayOfNumberOnly>(entityName: "ArrayOfArrayOfNumberOnly")
    }

    @NSManaged public var arrayArrayNumber: Set<Array>?

}

// MARK: Generated accessors for arrayArrayNumber
extension ArrayOfArrayOfNumberOnly {

    @objc(addArrayObject:)
    @NSManaged public func addArray(_ value: Array)

    @objc(removeArrayObject:)
    @NSManaged public func removeFromArray(_ value: Array)

    @objc(addArray:)
    @NSManaged public func addToArray(_ values: Set<Array>)

    @objc(removeArray:)
    @NSManaged public func removeFromArray(_ values: Set<Array>)
}
