/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen
* Do not edit the class manually.
*/

import Foundation
import CoreData

extension ArrayOfNumberOnly {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<ArrayOfNumberOnly> {
        return NSFetchRequest<ArrayOfNumberOnly>(entityName: "ArrayOfNumberOnly")
    }

    @NSManaged public var arrayNumber: Set<>?

}
