/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen
* Do not edit the class manually.
*/

import Foundation
import CoreData

extension Capitalization {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<Capitalization> {
        return NSFetchRequest<Capitalization>(entityName: "Capitalization")
    }

    var smallCamel: String? {
        get { return getManagedValue(key: "smallCamel") as? String }
        set { setManagedValue(newValue, key: "smallCamel") }
    }
var capitalCamel: String? {
        get { return getManagedValue(key: "capitalCamel") as? String }
        set { setManagedValue(newValue, key: "capitalCamel") }
    }
var smallSnake: String? {
        get { return getManagedValue(key: "smallSnake") as? String }
        set { setManagedValue(newValue, key: "smallSnake") }
    }
var capitalSnake: String? {
        get { return getManagedValue(key: "capitalSnake") as? String }
        set { setManagedValue(newValue, key: "capitalSnake") }
    }
var sCAETHFlowPoints: String? {
        get { return getManagedValue(key: "sCAETHFlowPoints") as? String }
        set { setManagedValue(newValue, key: "sCAETHFlowPoints") }
    }
var ATT_NAME: String? {
        get { return getManagedValue(key: "ATT_NAME") as? String }
        set { setManagedValue(newValue, key: "ATT_NAME") }
    }

}
