/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen
* Do not edit the class manually.
*/

import Foundation
import CoreData

extension Cat {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<Cat> {
        return NSFetchRequest<Cat>(entityName: "Cat")
    }

    var declawed: Bool? {
        get { return getManagedValue(key: "declawed") as? Bool }
        set { setManagedValue(newValue, key: "declawed") }
    }

}
