/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen
* Do not edit the class manually.
*/

import Foundation
import CoreData

extension ClassModel {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<ClassModel> {
        return NSFetchRequest<ClassModel>(entityName: "ClassModel")
    }

    var _class: String? {
        get { return getManagedValue(key: "_class") as? String }
        set { setManagedValue(newValue, key: "_class") }
    }

}
