/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen
* Do not edit the class manually.
*/

import Foundation
import CoreData

extension EnumArrays {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<EnumArrays> {
        return NSFetchRequest<EnumArrays>(entityName: "EnumArrays")
    }

    var justSymbol: String? {
        get { return getManagedValue(key: "justSymbol") as? String }
        set { setManagedValue(newValue, key: "justSymbol") }
    }
@NSManaged public var arrayEnum: Set<>?

}
