/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen
* Do not edit the class manually.
*/

import Foundation
import CoreData

extension EnumTest {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<EnumTest> {
        return NSFetchRequest<EnumTest>(entityName: "EnumTest")
    }

    var enumString: String? {
        get { return getManagedValue(key: "enumString") as? String }
        set { setManagedValue(newValue, key: "enumString") }
    }
var enumInteger: Int32? {
        get { return getManagedValue(key: "enumInteger") as? Int32 }
        set { setManagedValue(newValue, key: "enumInteger") }
    }
var enumNumber: Double? {
        get { return getManagedValue(key: "enumNumber") as? Double }
        set { setManagedValue(newValue, key: "enumNumber") }
    }
var outerEnum: OuterEnum? {
        get { return getManagedValue(key: "outerEnum") as? OuterEnum }
        set { setManagedValue(newValue, key: "outerEnum") }
    }

}
