/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen
* Do not edit the class manually.
*/

import Foundation
import CoreData

extension HasOnlyReadOnly {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<HasOnlyReadOnly> {
        return NSFetchRequest<HasOnlyReadOnly>(entityName: "HasOnlyReadOnly")
    }

    var bar: String? {
        get { return getManagedValue(key: "bar") as? String }
        set { setManagedValue(newValue, key: "bar") }
    }
var foo: String? {
        get { return getManagedValue(key: "foo") as? String }
        set { setManagedValue(newValue, key: "foo") }
    }

}
