/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen
* Do not edit the class manually.
*/

import Foundation
import CoreData

extension List {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<List> {
        return NSFetchRequest<List>(entityName: "List")
    }

    var _123List: String? {
        get { return getManagedValue(key: "_123List") as? String }
        set { setManagedValue(newValue, key: "_123List") }
    }

}
