/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen
* Do not edit the class manually.
*/

import Foundation
import CoreData

extension MapTest {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<MapTest> {
        return NSFetchRequest<MapTest>(entityName: "MapTest")
    }

    var mapMapOfString: Dictionary? {
        get { return getManagedValue(key: "mapMapOfString") as? Dictionary }
        set { setManagedValue(newValue, key: "mapMapOfString") }
    }
var mapOfEnumString: ? {
        get { return getManagedValue(key: "mapOfEnumString") as?  }
        set { setManagedValue(newValue, key: "mapOfEnumString") }
    }

}
