/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen
* Do not edit the class manually.
*/

import Foundation
import CoreData

extension MixedPropertiesAndAdditionalPropertiesClass {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<MixedPropertiesAndAdditionalPropertiesClass> {
        return NSFetchRequest<MixedPropertiesAndAdditionalPropertiesClass>(entityName: "MixedPropertiesAndAdditionalPropertiesClass")
    }

    var uuid: UUID? {
        get { return getManagedValue(key: "uuid") as? UUID }
        set { setManagedValue(newValue, key: "uuid") }
    }
var dateTime: Date? {
        get { return getManagedValue(key: "dateTime") as? Date }
        set { setManagedValue(newValue, key: "dateTime") }
    }
var map: Animal? {
        get { return getManagedValue(key: "map") as? Animal }
        set { setManagedValue(newValue, key: "map") }
    }

}
