/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen
* Do not edit the class manually.
*/

import Foundation
import CoreData

extension Model200Response {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<Model200Response> {
        return NSFetchRequest<Model200Response>(entityName: "Model200Response")
    }

    var name: Int32? {
        get { return getManagedValue(key: "name") as? Int32 }
        set { setManagedValue(newValue, key: "name") }
    }
var _class: String? {
        get { return getManagedValue(key: "_class") as? String }
        set { setManagedValue(newValue, key: "_class") }
    }

}
