/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen
* Do not edit the class manually.
*/

import Foundation
import CoreData

extension Name {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<Name> {
        return NSFetchRequest<Name>(entityName: "Name")
    }

    @NSManaged public var name: Int32 {
        get { return getManagedValue(key: "name") as? Int32 }
        set { setManagedValue(newValue, key: "name") }
    }
var snakeCase: Int32? {
        get { return getManagedValue(key: "snakeCase") as? Int32 }
        set { setManagedValue(newValue, key: "snakeCase") }
    }
var property: String? {
        get { return getManagedValue(key: "property") as? String }
        set { setManagedValue(newValue, key: "property") }
    }
var _123Number: Int32? {
        get { return getManagedValue(key: "_123Number") as? Int32 }
        set { setManagedValue(newValue, key: "_123Number") }
    }

}
