/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen
* Do not edit the class manually.
*/

import Foundation
import CoreData

extension NumberOnly {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<NumberOnly> {
        return NSFetchRequest<NumberOnly>(entityName: "NumberOnly")
    }

    var justNumber: Float? {
        get { return getManagedValue(key: "justNumber") as? Float }
        set { setManagedValue(newValue, key: "justNumber") }
    }

}
