/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen
* Do not edit the class manually.
*/

import Foundation
import CoreData

extension Order {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<Order> {
        return NSFetchRequest<Order>(entityName: "Order")
    }

    var id: Int64? {
        get { return getManagedValue(key: "id") as? Int64 }
        set { setManagedValue(newValue, key: "id") }
    }
var petId: Int64? {
        get { return getManagedValue(key: "petId") as? Int64 }
        set { setManagedValue(newValue, key: "petId") }
    }
var quantity: Int32? {
        get { return getManagedValue(key: "quantity") as? Int32 }
        set { setManagedValue(newValue, key: "quantity") }
    }
var shipDate: Date? {
        get { return getManagedValue(key: "shipDate") as? Date }
        set { setManagedValue(newValue, key: "shipDate") }
    }
var status: String? {
        get { return getManagedValue(key: "status") as? String }
        set { setManagedValue(newValue, key: "status") }
    }
var complete: Bool? {
        get { return getManagedValue(key: "complete") as? Bool }
        set { setManagedValue(newValue, key: "complete") }
    }

}
