/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen
* Do not edit the class manually.
*/

import Foundation
import CoreData

extension OuterComposite {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<OuterComposite> {
        return NSFetchRequest<OuterComposite>(entityName: "OuterComposite")
    }

    var myNumber: OuterNumber? {
        get { return getManagedValue(key: "myNumber") as? OuterNumber }
        set { setManagedValue(newValue, key: "myNumber") }
    }
var myString: OuterString? {
        get { return getManagedValue(key: "myString") as? OuterString }
        set { setManagedValue(newValue, key: "myString") }
    }
var myBoolean: OuterBoolean? {
        get { return getManagedValue(key: "myBoolean") as? OuterBoolean }
        set { setManagedValue(newValue, key: "myBoolean") }
    }

}
