/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen
* Do not edit the class manually.
*/

import Foundation
import CoreData

extension Pet {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<Pet> {
        return NSFetchRequest<Pet>(entityName: "Pet")
    }

    var id: Int64? {
        get { return getManagedValue(key: "id") as? Int64 }
        set { setManagedValue(newValue, key: "id") }
    }
var category: Category? {
        get { return getManagedValue(key: "category") as? Category }
        set { setManagedValue(newValue, key: "category") }
    }
@NSManaged public var name: String {
        get { return getManagedValue(key: "name") as? String }
        set { setManagedValue(newValue, key: "name") }
    }
@NSManaged public @NSManaged public var photoUrls: Set<>
@NSManaged public var tags: Set<Tag>?
var status: String? {
        get { return getManagedValue(key: "status") as? String }
        set { setManagedValue(newValue, key: "status") }
    }

}

// MARK: Generated accessors for tags
extension Pet {

    @objc(addTagObject:)
    @NSManaged public func addTag(_ value: Tag)

    @objc(removeTagObject:)
    @NSManaged public func removeFromTag(_ value: Tag)

    @objc(addTag:)
    @NSManaged public func addToTag(_ values: Set<Tag>)

    @objc(removeTag:)
    @NSManaged public func removeFromTag(_ values: Set<Tag>)
}
