/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen
* Do not edit the class manually.
*/

import Foundation
import CoreData

extension ReadOnlyFirst {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<ReadOnlyFirst> {
        return NSFetchRequest<ReadOnlyFirst>(entityName: "ReadOnlyFirst")
    }

    var bar: String? {
        get { return getManagedValue(key: "bar") as? String }
        set { setManagedValue(newValue, key: "bar") }
    }
var baz: String? {
        get { return getManagedValue(key: "baz") as? String }
        set { setManagedValue(newValue, key: "baz") }
    }

}
