/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen
* Do not edit the class manually.
*/

import Foundation
import CoreData

extension SpecialModelName {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<SpecialModelName> {
        return NSFetchRequest<SpecialModelName>(entityName: "SpecialModelName")
    }

    var specialPropertyName: Int64? {
        get { return getManagedValue(key: "specialPropertyName") as? Int64 }
        set { setManagedValue(newValue, key: "specialPropertyName") }
    }

}
